import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  bottomSheet: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,

    elevation: 9,
  },
  addIconImg: {
    width: 60,
    height: 60,
  },
  addIconImgContainer: {
    borderWidth: 5,
    borderRadius: 40,
    overflow: "hidden",
    borderColor: "#476C7D",
    zIndex: 1,
    top: -40,
    position: "absolute",
    elevation: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomAddIconView: {
    backgroundColor: "#EAF0F2",
    height: 320,
    alignItems: "center",
    flexDirection: "column",
    paddingTop: 30,
    paddingBottom: 10,
    position: "absolute",
    zIndex: 0,
    width: "100%",
  },
  bottomNavigationView: {
    backgroundColor: "#EAF0F2",
    height: 400,
    alignItems: "center",
    flexDirection: "column",
    paddingTop: 10,
    paddingBottom: 10,
    position: "relative",
    zIndex: 0,
  },
  button: {
    backgroundColor: "#75B0AF",
    alignSelf: "center",
    marginTop: 15,
    height: "15%",
    borderRadius: 10,
    justifyContent: "center",
    elevation: 3,
    width: "20%",
  },
  buttonsContainer: {
    flex: 3,
    flexWrap: "wrap",
    flexDirection: "row",
    marginTop: 20,
    paddingLeft: 20,
    paddingRight: 20,
    justifyContent: "center",
    alignItems: "center",
    width: 400,
  },
  closeIconContainer: {
    position: "absolute",
    right: "5%",
    top: "5%",
  },
  closeIconImg: {
    width: 20,
    height: 20,
  },
  descriptionContainer: {
    height: 60,
  },
  descriptionText: {
    backgroundColor: "#EAF0F2",
    borderRadius: 10,
    width: "80%",
    height: "95%",
    textAlignVertical: "top",
    padding: 2,
  },
  editContainer: {
    backgroundColor: "#CFE3E3",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 0,
    padding: 1,
    justifyContent: "space-between",
    elevation: 5,
  },
  generalText: {
    fontFamily: "K2D_600SemiBold",
    color: "#1C333E",
    textAlign: "center",
  },
  handiMarkerContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    borderStyle: "solid",
    marginRight: 4,
    marginBottom: 4,
    width: 100,
    position: "relative",
    zIndex: 0,
  },
  header: {
    fontSize: 20,
    width: "100%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#dcdddc",
    marginBottom: 1,
  },
  iconImg: {
    width: 60,
    height: 60,
    marginBottom: 3,
  },
  iconImgContainer: {
    elevation: 10,
    zIndex: 1,
    position: "relative",
  },
  iconText: {
    paddingLeft: 5,
  },
  iconTitleText: {
    color: "#B7CCD3",
    width: "100%",
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#dcdddc",
    marginBottom: 1,
  },
  locationContainer: {
    width: "100%",
  },
  markerImgWrapper: {
    zIndex: 1,
    elevation: 10,
  },
  placeNameText: {
    backgroundColor: "#EAF0F2",
    borderRadius: 10,
    width: "80%",
    height: 35,
    textAlign: "left",
  },
  propertyText: {
    paddingLeft: 15,
    fontFamily: "K2D_300Light_Italic",
    fontSize: 10,
    marginBottom: 2,
    marginTop: 10,
    textAlign: "left",
  },
  textStyle: {
    textAlign: "center",
    color: "#DEE7EA",
  },
  title: {
    flex: 1,
  },
});
